#!/bin/env bash

echo "This is the implode bootstrap script..."


# Check for RVM
if command -v rvm
then
    echo "Uninstalling rvm..."
    # rvm implode
    # rm -rf $HOME/.rvm
    # rm $HOME/.rvmrc
else
    echo "RVM is not installed."
fi
# Check for GIT
if command -v git
then
    echo "Uninstalling git..."
    # Remove git installation
else
    echo "Git is not installed."
fi

# Remove source directories used and general cleanup
if [ -d "$HOME/.src" ]; then
    rm -rf $HOME/.src
fi

if [ -d "$HOME/opt" ]; then
    rm -rf $HOME/opt
fi
