#!/bin/env bash

echo "This is the rvm bootstrap script..."

if command -v rvm
then
    echo "Git already installed."
    rvm=true
else
    echo "Installing rvm..."
    bash < <(curl -s https://raw.github.com/mtheoryx/rvm/master/binscripts/rvm-installer)
fi