#!/bin/env bash

git=false
rvm=false
ruby=false
gems=false

# Test for Git installed
if command -v git
then
    echo "Git already installed."
    git=true
else
    # Install git
    echo "Installing git..."
    bash < <(curl -s https://raw.github.com/mtheoryx/webserve_rvm/master/git_bootstrap)
fi

# Test for RVM installed
if command -v rvm
then
    rvm=true
    echo "RVM already installed."
else
    # Install rvm
    echo "Installing rvm..."
    # bash < <(curl -s https://raw.github.com/mtheoryx/webserve_rvm/master/rvm_bootstrap)
    bash < <(curl -s https://raw.github.com/mtheoryx/webserve_rvm/rvm/rvm_bootstrap)
fi

# Test for a Ruby installed
if command -v ruby
then
    ruby=true
    echo "Ruby already installed."
else
    # Install a rvm
    echo "Installing ruby..."
    bash < <(curl -s https://raw.github.com/mtheoryx/webserve_rvm/master/ruby_bootstrap)
fi

# Test for required Rubygems installed
echo "Gem test pending..."